data = [
    {"name": "Cristiano Ronaldo", "follower_count": 620, "description": "Footballer, athlete, icon", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 495, "description": "Football legend, World Cup winner", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "Singer, actress, Rare Beauty", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Beauty mogul, influencer", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 395, "description": "Actor, wrestler, tequila owner", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": 380, "description": "Singer, actress, pop star", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 370, "description": "Celebrity, businesswoman, influencer", "country": "USA"},
    {"name": "Beyoncé", "follower_count": 310, "description": "Singer, performer, queen bee", "country": "USA"},
    {"name": "Taylor Swift", "follower_count": 290, "description": "Singer-songwriter, global icon", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": 280, "description": "Pop singer, Canadian icon", "country": "Canada"},
    {"name": "Neymar Jr", "follower_count": 270, "description": "Footballer, Brazilian star", "country": "Brazil"},
    {"name": "Kendall Jenner", "follower_count": 260, "description": "Model, influencer, celebrity", "country": "USA"},
    {"name": "National Geographic", "follower_count": 250, "description": "Nature photography and exploration", "country": "USA"},
    {"name": "Nike", "follower_count": 240, "description": "Sportswear, global brand", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 230, "description": "Cricketer, Indian captain", "country": "India"},
    {"name": "Jennifer Lopez", "follower_count": 225, "description": "Singer, actress, dancer", "country": "USA"},
    {"name": "Zendaya", "follower_count": 220, "description": "Actress, model, style icon", "country": "USA"},
    {"name": "Kourtney Kardashian", "follower_count": 210, "description": "Celebrity, businesswoman", "country": "USA"},
    {"name": "Miley Cyrus", "follower_count": 205, "description": "Singer, actress, rebel", "country": "USA"},
    {"name": "Cardi B", "follower_count": 200, "description": "Rapper, entertainer, outspoken", "country": "USA"},
    {"name": "Dua Lipa", "follower_count": 195, "description": "Singer, performer, fashion icon", "country": "UK"},
    {"name": "Drake", "follower_count": 190, "description": "Rapper, singer, Canadian star", "country": "Canada"},
    {"name": "LeBron James", "follower_count": 185, "description": "Basketball legend, philanthropist", "country": "USA"},
    {"name": "Shakira", "follower_count": 180, "description": "Singer, performer, hips don’t lie", "country": "Colombia"},
    {"name": "Billie Eilish", "follower_count": 175, "description": "Singer, songwriter, Grammy winner", "country": "USA"},
    {"name": "Bad Bunny", "follower_count": 170, "description": "Reggaeton artist, Latin icon", "country": "Puerto Rico"},
    {"name": "Rihanna", "follower_count": 165, "description": "Singer, Fenty founder, billionaire", "country": "Barbados"},
    {"name": "Emma Watson", "follower_count": 160, "description": "Actress, activist, book lover", "country": "UK"},
    {"name": "Chris Hemsworth", "follower_count": 155, "description": "Actor, Thor, Australian star", "country": "Australia"},
    {"name": "Shawn Mendes", "follower_count": 150, "description": "Singer, songwriter, Canadian idol", "country": "Canada"},
    {"name": "Gal Gadot", "follower_count": 145, "description": "Wonder Woman, actress, model", "country": "Israel"},
    {"name": "Will Smith", "follower_count": 140, "description": "Actor, rapper, Fresh Prince", "country": "USA"},
    {"name": "Zlatan Ibrahimović", "follower_count": 135, "description": "Footballer, lion, confident", "country": "Sweden"},
    {"name": "Post Malone", "follower_count": 130, "description": "Rapper, singer, unique style", "country": "USA"},
    {"name": "Millie Bobby Brown", "follower_count": 125, "description": "Stranger Things, actress, Gen Z", "country": "UK"},
    {"name": "Camila Cabello", "follower_count": 120, "description": "Singer, Havana hitmaker", "country": "USA"},
    {"name": "David Beckham", "follower_count": 115, "description": "Football legend, style icon", "country": "UK"},
    {"name": "Gigi Hadid", "follower_count": 110, "description": "Model, fashion, Vogue star", "country": "USA"},
    {"name": "Zayn Malik", "follower_count": 105, "description": "Singer, ex-One Direction", "country": "UK"},
    {"name": "Blake Lively", "follower_count": 100, "description": "Actress, style icon, mom", "country": "USA"},
    {"name": "Pedro Pascal", "follower_count": 98, "description": "Actor, Mandalorian, Chilean star", "country": "Chile"},
    {"name": "Olivia Rodrigo", "follower_count": 96, "description": "Singer, breakout star, actress", "country": "USA"},
    {"name": "Jungkook", "follower_count": 95, "description": "BTS singer, K-pop star", "country": "South Korea"},
    {"name": "Tom Holland", "follower_count": 94, "description": "Spider-Man, actor, charming", "country": "UK"},
    {"name": "Doja Cat", "follower_count": 92, "description": "Rapper, singer, internet icon", "country": "USA"},
    {"name": "Harry Styles", "follower_count": 90, "description": "Singer, ex-One Direction", "country": "UK"},
    {"name": "Lisa (BLACKPINK)", "follower_count": 89, "description": "K-pop idol, dancer, Thai", "country": "Thailand"},
    {"name": "Robert Downey Jr", "follower_count": 88, "description": "Iron Man, actor, legend", "country": "USA"},
    {"name": "Snoop Dogg", "follower_count": 85, "description": "Rapper, icon, West Coast", "country": "USA"}
]
